language: cpp

os:
 - linux
 - osx

env:
 - DESIRED_QT_VERSION=4
 - DESIRED_QT_VERSION=5

sudo: required
dist: trusty

before_install:
  - git submodule update --init --recursive
  - bash testing/travis-scripts/install-deps.sh

script:
  - bash testing/travis-scripts/build-test.sh
