language: cpp

os:
 - linux

matrix:
  include:
    - compiler: gcc
      env:
      - DESIRED_QT_VERSION=4
      - SWIG_VERSION=2
    - compiler: gcc
      env:
      - DESIRED_QT_VERSION=5
      - SWIG_VERSION=3
    - compiler: clang
      env:
      - DESIRED_QT_VERSION=4
      - SWIG_VERSION=2
    - compiler: clang
      env:
      - DESIRED_QT_VERSION=5
      - SWIG_VERSION=3

sudo: required
dist: trusty

before_install:
  - git submodule update --init --recursive
  - bash testing/travis-scripts/install-deps.sh

script:
  - bash testing/travis-scripts/build-test.sh
