language: cpp

os:
 - linux

matrix:
  include:
    # Default/older GCC, dependencies
    - compiler: gcc
      env:
        - DESIRED_QT_VERSION=4
        - PYTHON_VERSION=2
        - RUBY_VERSION=2.3
        - SWIG_VERSION=2
    # Newer GCC, dependencies
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:brightbox/ruby-ng'
            - sourceline: 'ppa:rosmo/swig3.0.7'
          packages:
            - g++-6
            - swig3.0
      env:
        - NEWCC=gcc-6
        - NEWCXX=g++-6
        - DESIRED_QT_VERSION=5
        - PYTHON_VERSION=3
        - RUBY_VERSION=2.4
        - SWIG_VERSION=3
    # Default/older Clang, dependencies
    - compiler: clang
      env:
        - DESIRED_QT_VERSION=4
        - PYTHON_VERSION=2
        - RUBY_VERSION=2.3
        - SWIG_VERSION=2
    # Newer Clang, dependencies
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - sourceline: 'ppa:brightbox/ruby-ng'
            - sourceline: 'ppa:rosmo/swig3.0.7'
          packages:
            - clang-4.0
            - ruby2.4
            - swig3.0
      env:
        - NEWCC=clang-4.0
        - NEWCXX=clang++-4.0
        - DESIRED_QT_VERSION=5
        - PYTHON_VERSION=3
        - RUBY_VERSION=2.4
        - SWIG_VERSION=3

sudo: required
dist: trusty

before_install:
  - git submodule update --init --recursive
  - bash testing/travis-scripts/install-deps.sh

script:
  - bash testing/travis-scripts/build-test.sh
