language: cpp

os:
 - linux

env:
 - DESIRED_QT_VERSION=4
 - DESIRED_QT_VERSION=5

sudo: required
dist: trusty

before_install:
  - git submodule update --init --recursive
  - bash testing/travis-scripts/install-deps.sh

before_script:
  - "export DISPLAY=99:0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - bash testing/travis-scripts/build-test.sh
