environment:
  LUAROCKS_VER: 2.3.0
  matrix:
#    - BITNESS: 32
#      CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
#      BOOST_VERSION: 1_59
#      QT_DIR: "C:\\Qt\\5.6\\msvc2015"
#      PYTHON_VERSION: 35
#      LUA_VER: 5.1.5
#
#    - BITNESS: 64
#      CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
#      BOOST_VERSION: 1_59
#      QT_DIR: "C:\\Qt\\5.6\\msvc2015_64"
#      PYTHON_VERSION: 35
#      LUA_VER: 5.1.5
#
#    - BITNESS: 32
#      CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
#      BOOST_VERSION: 1_62
#      QT_DIR: "C:\\Qt\\5.7\\msvc2015"
#      PYTHON_VERSION: 35
#      LUA_VER: 5.2.4
#
#    - BITNESS: 64
#      CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
#      BOOST_VERSION: 1_62
#      QT_DIR: "C:\\Qt\\5.7\\msvc2015_64"
#      PYTHON_VERSION: 35
#      LUA_VER: 5.2.4
#
#    - BITNESS: 32
#      CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
#      BOOST_VERSION: 1_63
#      QT_DIR: "C:\\Qt\\5.8\\msvc2015"
#      PYTHON_VERSION: 35
#      LUA_VER: 5.3.2
#
#    - BITNESS: 64
#      CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
#      BOOST_VERSION: 1_63
#      QT_DIR: "C:\\Qt\\5.8\\msvc2015_64"
#      PYTHON_VERSION: 35
#      LUA_VER: 5.3.2

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BITNESS: 32
      CMAKE_GENERATOR_NAME: "Visual Studio 15 2017"
      BOOST_VERSION: 1_64
      QT_DIR: "C:\\Qt\\5.9.1\\msvc2017"
      PYTHON_VERSION: 35
      LUA_VER: 5.3.2

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BITNESS: 64
      CMAKE_GENERATOR_NAME: "Visual Studio 15 2017 Win64"
      BOOST_VERSION: 1_64
      QT_DIR: "C:\\Qt\\5.9.1\\msvc2017_64"
      PYTHON_VERSION: 35
      LUA_VER: 5.3.2

configuration: Release

cache:
  - C:\lua -> testing\appveyor-scripts\build-test.bat
  - C:\external -> testing\appveyor-scripts\build-test.bat

install:
  - git submodule update --init --recursive
  - choco install -y doxygen.install swig
  - testing\appveyor-scripts\lua\set_compiler_env.bat
  - testing\appveyor-scripts\lua\install.bat
  - luarocks install luaunit

build_script:
  - testing\appveyor-scripts\build-test.bat

test: off
