environment:
  LUAROCKS_VER: 2.3.0
  matrix:
    - BITNESS: 32
      BOOST_VERSION: 1_63_0
      PYTHON_VERSION: 35
      LUA_VER: 5.1.5
      RUBY_VERSION: 22

    - BITNESS: 64
      BOOST_VERSION: 1_63_0
      PYTHON_VERSION: 35
      LUA_VER: 5.1.5
      RUBY_VERSION: 22-x64

    - BITNESS: 32
      BOOST_VERSION: 1_65_1
      PYTHON_VERSION: 35
      LUA_VER: 5.2.4
      RUBY_VERSION: 23

    - BITNESS: 64
      BOOST_VERSION: 1_65_1
      PYTHON_VERSION: 35
      LUA_VER: 5.2.4
      RUBY_VERSION: 23-x64

    - BITNESS: 32
      BOOST_VERSION: 1_67_1
      PYTHON_VERSION: 35
      LUA_VER: 5.3.2
      RUBY_VERSION: 24

    - BITNESS: 64
      BOOST_VERSION: 1_67_1
      PYTHON_VERSION: 35
      LUA_VER: 5.3.2
      RUBY_VERSION: 24-x64

configuration: Release

cache:
  - C:\lua -> testing\appveyor-scripts\build-test.bat
  - C:\external -> testing\appveyor-scripts\build-test.bat

install:
  - git submodule update --init --recursive
  - choco install -y doxygen.install swig
  - testing\appveyor-scripts\lua\set_compiler_env.bat
  - testing\appveyor-scripts\lua\install.bat
  - luarocks install luaunit

build_script:
  - testing\appveyor-scripts\build-test.bat

test: off
