environment:
  LUAROCKS_VER: 2.3.0
  matrix:
    - BITNESS: 32
      CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
      BOOST_VERSION: 1_59
      PYTHON_VERSION: 35
      LUA_VER: 5.1.5

    - BITNESS: 64
      CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
      BOOST_VERSION: 1_59
      PYTHON_VERSION: 35
      LUA_VER: 5.1.5

    - BITNESS: 32
      CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
      BOOST_VERSION: 1_62
      PYTHON_VERSION: 35
      LUA_VER: 5.2.4

    - BITNESS: 64
      CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
      BOOST_VERSION: 1_62
      PYTHON_VERSION: 35
      LUA_VER: 5.2.4

    - BITNESS: 32
      CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
      BOOST_VERSION: 1_63
      PYTHON_VERSION: 35
      LUA_VER: 5.3.2

    - BITNESS: 64
      CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
      BOOST_VERSION: 1_63
      PYTHON_VERSION: 35
      LUA_VER: 5.3.2

configuration: Release

cache:
  - C:\lua -> testing\appveyor-scripts\build-test.bat
  - C:\external -> testing\appveyor-scripts\build-test.bat

install:
  - git submodule update --init --recursive
  - choco install -y doxygen.install swig
  - testing\appveyor-scripts\lua\set_compiler_env.bat
  - testing\appveyor-scripts\lua\install.bat
  - luarocks install luaunit

build_script:
  - testing\appveyor-scripts\build-test.bat

test: off
